# Generated by Django 5.1.5 on 2025-02-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0002_log_command'),
        ('api_room', '0011_iotobject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='iotObject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='iot_object', to='api_room.iotobject'),
        ),
    ]
