# Generated by Django 5.1.5 on 2025-02-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0003_alter_log_iotobject'),
        ('api_room', '0011_iotobject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='iotObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='log', to='api_room.iotobject'),
        ),
    ]
