# Generated by Django 5.1.5 on 2025-02-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0004_alter_log_iotobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
