# Generated by Django 5.1.5 on 2025-02-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0005_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
