# Generated by Django 5.1.5 on 2025-02-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_control', '0007_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
