# Generated by Django 5.1.5 on 2025-02-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coordinators', models.ManyToManyField(to='api_auth.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('admin', models.ManyToManyField(to='api_auth.admin')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_room.departament')),
                ('users', models.ManyToManyField(to='api_auth.common')),
            ],
        ),
        migrations.CreateModel(
            name='IOTObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_room.room')),
            ],
        ),
    ]
