# Generated by Django 5.1.5 on 2025-02-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
        ('api_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Department',
        ),
    ]
