# Generated by Django 5.1.5 on 2025-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0001_initial'),
        ('api_room', '0002_rename_departament_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='coordinators',
            field=models.ManyToManyField(to='api_permission.coordinator'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ManyToManyField(to='api_permission.admin'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='api_permission.common'),
        ),
    ]
