# Generated by Django 5.1.5 on 2025-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_permission', '0001_initial'),
        ('api_room', '0003_alter_department_coordinators_alter_room_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='coordinators',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to='api_permission.coordinator'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='api_permission.admin'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='api_permission.common'),
        ),
    ]
