# Generated by Django 5.1.5 on 2025-02-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0005_alter_department_coordinators_alter_room_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api_room.department'),
        ),
    ]
