# Generated by Django 5.1.5 on 2025-02-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0006_alter_room_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='departament',
            new_name='department',
        ),
    ]
