# Generated by Django 5.1.5 on 2025-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0007_rename_departament_room_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotobject',
            name='status',
            field=models.CharField(blank=True, default='Esperando', max_length=50),
        ),
    ]
