# Generated by Django 5.1.5 on 2025-02-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0008_iotobject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotobject',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_room.room'),
        ),
    ]
