# Generated by Django 5.1.5 on 2025-02-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0009_alter_iotobject_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotobject',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='iotobjects', to='api_room.room'),
        ),
    ]
