# Generated by Django 5.1.5 on 2025-02-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_room', '0010_alter_iotobject_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotobject',
            name='description',
            field=models.CharField(default='Porta', max_length=100),
        ),
    ]
