# Generated by Django 5.1.5 on 2025-02-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
        ('api_room', '0003_alter_department_coordinators_alter_room_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
